name: Node.js CI

on:
  schedule:
    - cron: "0 2 * * *"  # Runs every day at 2:00 AM UTC
  push:
    branches: [ "development" ]
  pull_request:

jobs:
  backup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # choose one stable Node.js version

    defaults:
        run:
            working-directory: backend # set default working directory
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json # point cache to backend

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Run backup script
        run: npm run backup
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
